# Generated by Django 6.1 on 2026-09-08 00:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('territorio', models.CharField(max_length=180)),
                ('enfasis', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'delegación',
                'verbose_name_plural': 'delegaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=80)),
                ('identificador', models.CharField(max_length=80)),
                ('detalle', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('solicitante', models.CharField(max_length=160)),
                ('territorio', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('fecha_comprometida', models.DateField()),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('realizado', 'Realizado')], default='ingresado', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to=settings.AUTH_USER_MODEL)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='delegaciones_app.delegacion')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=32, unique=True)),
                ('fecha', models.DateField()),
                ('tipo_atencion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('accion', models.TextField()),
                ('item_medicion', models.CharField(max_length=160)),
                ('contacto', models.CharField(blank=True, max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to=settings.AUTH_USER_MODEL)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='delegaciones_app.delegacion')),
            ],
            options={
                'ordering': ['-fecha', '-creada'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('comentario', models.TextField(blank=True)),
                ('aprobada', models.BooleanField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='delegaciones_app.actividad')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('objetivo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('avance', models.PositiveIntegerField(default=0)),
                ('ponderador', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('periodo_inicio', models.DateField()),
                ('periodo_termino', models.DateField()),
                ('tope_cumplimiento', models.DecimalField(decimal_places=2, default=150, max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='delegaciones_app.delegacion')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador'), ('delegado', 'Delegado'), ('funcionario', 'Funcionario'), ('verificador', 'Verificador'), ('consulta', 'Consulta')], default='consulta', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='delegaciones_app.delegacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
