# Generated by Django 6.1 on 2026-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones_app', '0002_historialcompromiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('version_parametros', models.PositiveIntegerField(default=1)),
                ('umbral_colectivo', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
                ('maximo_cumplimiento', models.DecimalField(decimal_places=2, default=150, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('actividad', 'Actividad'), ('servicio', 'Servicio'), ('atencion', 'Tipo de atención'), ('item', 'Ítem de medición')], max_length=20)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'codigo'), name='catalogo_categoria_codigo_unico')],
            },
        ),
    ]
